services:
  status:
    container_name: status
    restart: always
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html:ro
    networks:
      - "net"
    mem_limit: 50mb
  amialive:
    container_name: amialive
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: amialived
    volumes:
      - ./config.toml:/app/config.toml
    networks:
      - "net"
    mem_limit: 50mb

networks:
  net:
    external: true

