services:
  status:
    container_name: status
    restart: always
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html:ro
    networks:
      - "amialivenet"
    ports:
      - "80:80"
    mem_limit: 50mb
  amialive:
    container_name: amialive
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: amialived
    volumes:
      - ./config.toml:/app/config.toml
      - ./db.txt:/app/db.txt
    networks:
      - "amialivenet"
    mem_limit: 50mb

networks:
  amialivenet:
    name: Am I Alive Network
    driver: bridge
