[global]
name = "John"
full_name = "John Doe"
time_until_uncertain = 24 # in hours
time_until_death = 168 # 1 week in hours
pow_difficulty = 5 # See: https://blog.trishtzy.com/2025/08/15/rate-limit-by-pow.html
heartbeat_auth_hash = "<ARGON2ID HASH>"
ok_images = ["/resources/happy-cat.webp"]
ok_messages = ["{0} is alive and well. Thank you for checking."]
uncertain_message = "{0} has not sent a heartbeat in the past {1} hours."
death_images = ["/resources/sad-cat.webp"]
death_message = "{0} has passed away."
