[global]
name = "John"
full_name = "John Doe"
utc_offset = 0
heartbeat_auth_hash = "<ARGON2ID HASH>"

[pow]
# Generate the following secret using `openssl rand -hex 32`.
# This is used when generating PoW challenges; It ensures a client cannot guess
# what the next generated challenge will be, which blocks pre-computation attacks.
secret = "<256-BIT SECRET>"
# PoW difficulty. Already set to the recommended default.
# See: https://blog.trishtzy.com/2025/08/15/rate-limit-by-pow.html
difficulty = 4

[state]
tick_interval = 60 # in minutes
time_until_uncertain = 24 # in hours
time_until_missing = 72 # in hours
# Minimum server up-time required to make an autonomous state change.
# Safety net for sysadmins bringing back up the service after maintenance.
minimum_uptime = 60 # in minutes

[state.alive]
images = [
    "/resources/happy-cat.webp",
    "/resources/happy-cat-2.gif",
    "/resources/happy-cat-3.gif",
    "/resources/disco-cat.gif",
    "/resources/dancing-cat.gif",
    "/resources/dancing-cat-2.gif",
]
messages = [
    "{0} is alive and well. Thank you for checking.",
    "{0} is alive and well. We checked.",
    "{0} is alive and well. Send snacks.",
    "{0} is alive and well. Send cats.",
    "{0} is still with us, don't worry.",
    "{0} is still alive. Check again tomorrow.",
    "{0} is still alive and uncontained.",
    "{0} is still alive so far. Yay",
    "{0} is alive... Would be crazy if they weren't",
    "{0} is still alive. What made you check?",
    "{0} is still alive. Might not be anymore if you refresh...",
]

[state.uncertain]
images = ["/resources/worried-cat.webp"]
messages = ["{0} has not sent a heartbeat in the past {1} hour{2}."]

[state.missing]
images = ["/resources/worried-cat.webp"]
messages = ["{0} has not sent a heartbeat in the past {1} hour{2}."]

[state.incapacitated]
images = ["/resources/worried-cat.webp"]
messages = ["{0} has not sent a heartbeat in the past {1} hour{2}."]

[state.dead]
images = ["/resources/sad-cat.webp"]
messages = ["{0} has passed away."]
